In [1]:
import torch

In [ ]:
a = torch.tensor([1, 2, 3])
a.shape

torch.Size([3])

In [8]:
a.unsqueeze_(dim=0)
a.shape

torch.Size([1, 3])

In [ ]:
ten = torch.tensor([1, 2, 3], dtype=torch.float32)

In [20]:
ten.unsqueeze_(dim=0)

tensor([[1., 2., 3.]])

In [21]:
ten.unsqueeze_(dim=2)

tensor([[[1.],
         [2.],
         [3.]]])

In [28]:
ten[0].shape

torch.Size([3, 1])

In [30]:
ten[0:1].shape

torch.Size([1, 3, 1])

In [ ]:
lstm = torch.nn.GRU(1, 10, 1)


In [23]:
lstm(ten)

(tensor([[[-0.1323, -0.0800, -0.1023,  0.1683, -0.1461, -0.1371, -0.0140,
           -0.0557, -0.1142,  0.0897],
          [-0.1386, -0.2214, -0.2417,  0.1903, -0.2806, -0.1648,  0.0467,
           -0.0488, -0.2562,  0.2577],
          [-0.1361, -0.3316, -0.3468,  0.2115, -0.4170, -0.1841,  0.0846,
           -0.0425, -0.3937,  0.3929]]], grad_fn=<StackBackward0>),
 tensor([[[-0.1323, -0.0800, -0.1023,  0.1683, -0.1461, -0.1371, -0.0140,
           -0.0557, -0.1142,  0.0897],
          [-0.1386, -0.2214, -0.2417,  0.1903, -0.2806, -0.1648,  0.0467,
           -0.0488, -0.2562,  0.2577],
          [-0.1361, -0.3316, -0.3468,  0.2115, -0.4170, -0.1841,  0.0846,
           -0.0425, -0.3937,  0.3929]]], grad_fn=<StackBackward0>))

In [ ]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [ ]:
print(t.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [31]:
date_vreme = torch.tensor(
    [
        [15, 16, 17],  # Ziua 1
        [12, 14, 13],  # Ziua 2
    ]
)


In [43]:
date_vreme[1:2, :]

tensor([[12, 14, 13]])

In [ ]:
data_vreme3d = date_vreme.unsqueeze(dim=2)

In [45]:
data_vreme3d

tensor([[[15],
         [16],
         [17]],

        [[12],
         [14],
         [13]]])

In [ ]:
logits = torch.tensor(
    [
        [2.5, -1.0, 0.2, 1.1],  # Scorurile pentru imaginea 1
        [-0.5, 3.2, -1.5, 0.1],  # Scorurile pentru imaginea 2
        [0.3, 0.1, 4.5, -0.2],  # Scorurile pentru imaginea 3
    ]
)

In [52]:
print(logits.argmax(dim=1))


tensor([0, 1, 2])
